version: 0.0
os: linux

files:
  - source: ./
    destination: /home/ubuntu

hooks:
  ApplicationStop:
    - location: ./applicationStop.sh
      timeout: 300

  BeforeInstall:
    - location: ./beforeInstall.sh
      timeout: 300

  AfterInstall:
    - location: ./afterInstall.sh
      timeout: 1000

  ApplicationStart:
    - location: ./applicationStart.sh
      timeout: 300